stages:
    - publish

variables:
    GITHUB_TOKEN: $demo_github_pat

deploy_to_github:
    stage: publish
    script:
        - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/aajarven/lab-hub-demo.git || echo "remote already exists"
        - git checkout main
        - git merge --ff-only origin/main
        - git status
        - git log --oneline --all --decorate
        - git remote -v
        - git push github main:publish/main
    tags:
        - kp-demo
    only:
        - main
